// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Dashboard.Infrastructure.Data;

#nullable disable

namespace Dashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221206142854_add-Accounts")]
    partial class addAccounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dashboard.Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("BuildNo")
                        .HasColumnType("longtext");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Exten")
                        .HasColumnType("longtext");

                    b.Property<string>("Flat")
                        .HasColumnType("longtext");

                    b.Property<string>("Floor")
                        .HasColumnType("longtext");

                    b.Property<int>("GovId")
                        .HasColumnType("int");

                    b.Property<int?>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("LandMark")
                        .HasColumnType("longtext");

                    b.Property<string>("MainStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel2")
                        .HasColumnType("longtext");

                    b.Property<string>("Tel3")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("BranId")
                        .HasColumnType("int");

                    b.Property<int?>("GovId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BranId");

                    b.HasIndex("GovId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Delivery")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Governorates");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.Account", b =>
                {
                    b.HasOne("Dashboard.Core.Entities.City", null)
                        .WithMany("Account")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard.Core.Entities.District", null)
                        .WithMany("Account")
                        .HasForeignKey("DistrictId");

                    b.HasOne("Dashboard.Core.Entities.Governorate", null)
                        .WithMany("Account")
                        .HasForeignKey("GovernorateId");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.City", b =>
                {
                    b.HasOne("Dashboard.Core.Entities.Branch", "Branch")
                        .WithMany("City")
                        .HasForeignKey("BranId");

                    b.HasOne("Dashboard.Core.Entities.Governorate", "Gov")
                        .WithMany("City")
                        .HasForeignKey("GovId");

                    b.Navigation("Branch");

                    b.Navigation("Gov");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.District", b =>
                {
                    b.HasOne("Dashboard.Core.Entities.City", "City")
                        .WithMany("District")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.Branch", b =>
                {
                    b.Navigation("City");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.City", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.District", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("Dashboard.Core.Entities.Governorate", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
